name: Qodana

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}        
        with:
          args: --property, qodana.net.solution=NopCommerce.sln 
